-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 8 de set. de 2022
-- Time: 11:20:19
-- By Wesley
-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 1 de set. de 2022
-- Time: 17:06:49
-- By Wesley
---- TABELA DERIVADA
SELECT
FCH_TRANS.*,
(
  SELECT 
--  FIRST 1
  SHPRETRA.ID_PRETRANS 
  FROM SHPRETRA SHPRETRA
  JOIN SHBOLSA SHBOLSA  ON SHPRETRA.ID_BOLSA  = SHBOLSA.ID_BOLSA 
  WHERE 
  SUBSTRING(SHPRETRA."DATA" FROM 1 FOR 10)   =  CURRENT_DATE 
  AND 
   NOT EXISTS ( SELECT
                *
               FROM SHTRANS 
               WHERE 
               SHPRETRA.ID_PRETRANS = SHTRANS.ID_SHPRETRA 
              )
)
----TABELA PRINCIPAL-------------------------
FROM (
SELECT 
DISTINCT 
ATCABECATEND.TP_ATENDIMENTO ,--TIPO DE ATENDIMENTO
ATCABECATEND.DATA_HORA_ENTRADA,
---- PRONTUARIO
(SELECT
RICADPAC.PRONT
FROM
RICADPAC RICADPAC2
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC2.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID
AND RICADPAC2.ID = HTPACIENTE.ID_RICADPAC
)PRONT ,
---- REGISTRO 

CASE
ATCABECATEND.TP_ATENDIMENTO WHEN 'I' THEN
(--REGISTRO INTERNO
SELECT
RICADPAC.REG
FROM
RICADPAC RICADPAC
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID)
--REGISTRO EXTERNO
WHEN 'E' THEN (
SELECT
RECADATE.REG
FROM
RECADATE RECADATE
INNER JOIN ATCABECATEND ATCABECATEND02 ON
ATCABECATEND02.ID = RECADATE.ID_ATCABECATEND
WHERE
ATCABECATEND02.ID = ATCABECATEND.ID )END 
REGISTRO,

-- NOME 
(
SELECT
RICADPAC.NOME
FROM
RICADPAC RICADPAC
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID
)PACIENTE,
----DATA DE NASCIMENTO
RICADPAC.NASC AS NASC
     
FROM
ATCABECATEND ATCABECATEND
INNER JOIN HTATENDIMENTO HTATENDIMENTO ON
HTATENDIMENTO.ID_ATCABECATEND = ATCABECATEND.ID
INNER JOIN TBUNIDAD TBUNIDAD ON
TBUNIDAD.COD = HTATENDIMENTO.ID_TBUNIDAD
INNER JOIN RICADPAC RICADPAC ON
RICADPAC.ID = ATCABECATEND.ID_RICADPAC
INNER JOIN HTPACIENTE HTPACIENTE ON
HTPACIENTE.ID_RICADPAC = RICADPAC .ID
INNER JOIN TBRELIG TBRELIG ON
TBRELIG.COD = RICADPAC.RELIG
--INNER JOIN SHTRANS SHTRANS ON 
--SHTRANS.REG  = ATCABECATEND.COD_ATENDIMENTO 
--AND SHTRANS.ATEND = ATCABECATEND.TP_ATENDIMENTO
--RIGHT  JOIN SHPRETRA SHPRETRA ON
--SHPRETRA.ID_PRETRANS = SHTRANS.ID_SHPRETRA
--INNER JOIN SHBOLSA SHBOLSA ON 
--SHBOLSA.ID_BOLSA = SHPRETRA.ID_BOLSA
/*
WHERE
ATCABECATEND.COD_ATENDIMENTO=:ATENDIMENTO_REGISTRO
AND
RICADPAC.PRONT=:PACIENTE_PRONTUARIO*/
--ORDER BY ATCABECATEND.ID DESC 
ORDER BY PACIENTE

)FCH_TRANS