-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 1 de set. de 2022
-- Time: 17:06:49
-- By Wesley
---- TABELA DERIVADA
SELECT
FCH_TRANS.*,

--DATA_ULT_BOLSA
COALESCE((
SELECT  FIRST 1
SHTRANS.DATAI
FROM SHTRANS SHTRANS 
INNER JOIN SHBOLSA SHBOLSA ON SHTRANS.ID_BOLSA=SHBOLSA.ID_BOLSA
INNER JOIN SITABPRO SITABPRO ON SHBOLSA.HEMOCOMPONENTE=SITABPRO.CODALF AND SITABPRO.ATO=99
LEFT JOIN RICADINT RICADINT  ON SHTRANS.REG=RICADINT.REG AND SHTRANS.ATEND= 'I'
LEFT JOIN RECADATE RECADATE ON SHTRANS.REG=RECADATE.REG AND SHTRANS.ATEND= 'E'
INNER JOIN SHTECNIC SHTECNIC ON SHTECNIC.CRM_TECNICO=SHTRANS.CRM_TECNICO
INNER JOIN RICADPAC RICADPAC ON RICADPAC.PRONT=RICADINT.PRONT OR (RICADPAC.PRONT=RECADATE.PRONT)
LEFT  JOIN SHPRETRA SHPRETRA ON SHTRANS.REG= SHPRETRA.REG AND SHTRANS.ATEND=SHPRETRA.ATEND AND  SHTRANS.ID_BOLSA=SHPRETRA.ID_BOLSA
WHERE SHTRANS.ID_TRANS>0 AND
--RICADPAC.PRONT =:FCH_TRANS
RICADPAC.PRONT = FCH_TRANS.PRONT
ORDER BY SHTRANS.DATA DESC ),
'----',(SELECT  FIRST 1
SHTRANS.DATAI
FROM SHTRANS SHTRANS 
INNER JOIN SHBOLSA SHBOLSA ON SHTRANS.ID_BOLSA=SHBOLSA.ID_BOLSA
INNER JOIN SITABPRO SITABPRO ON SHBOLSA.HEMOCOMPONENTE=SITABPRO.CODALF AND SITABPRO.ATO=99
LEFT JOIN RICADINT RICADINT  ON SHTRANS.REG=RICADINT.REG AND SHTRANS.ATEND= 'I'
LEFT JOIN RECADATE RECADATE ON SHTRANS.REG=RECADATE.REG AND SHTRANS.ATEND= 'E'
INNER JOIN SHTECNIC SHTECNIC ON SHTECNIC.CRM_TECNICO=SHTRANS.CRM_TECNICO
INNER JOIN RICADPAC RICADPAC ON RICADPAC.PRONT=RICADINT.PRONT OR (RICADPAC.PRONT=RECADATE.PRONT)
LEFT  JOIN SHPRETRA SHPRETRA ON SHTRANS.REG= SHPRETRA.REG AND SHTRANS.ATEND=SHPRETRA.ATEND AND  SHTRANS.ID_BOLSA=SHPRETRA.ID_BOLSA
WHERE SHTRANS.ID_TRANS>0 AND
--RICADPAC.PRONT =:FCH_TRANS
RICADPAC.PRONT = FCH_TRANS.PRONT
ORDER BY SHTRANS.DATA DESC))
AS DATA_ULT_BOLSA,

--SANGUE
FCH_TRANS.SANGUE,
--FATOR RH SANGUE
     DECODE( FCH_TRANS.FATOR_RH,
                  1,'POSITIVO',
                  2, 'NEGATIVO',
                  ' ') AS RH,
  
---RESULTADO HB                    
FCH_TRANS.HB_INDEX,
SUBSTRING( 
'Hb '|| 
(       
         SELECT 
              FIRST 1
               SIRES01.NUMERICO
              FROM SIRES01 SIRES01 
              WHERE 
              SIRES01.ELEMENTO = 3
              AND 
              SIRES01.EXAME = 'HG' 
              AND 
              FCH_TRANS.HB_INDEX = SIRES01.ID_SILANEXA 
                  )FROM 1 FOR 7) || ' g%' AS hb ,
FCH_TRANS.HT_INDEX, 

--RESULTADO HT
 SUBSTRING(
'Ht '|| 
(       
         SELECT 
              FIRST 1
               SIRES01.NUMERICO
              FROM SIRES01 SIRES01 
              WHERE 
              SIRES01.ELEMENTO = 4
              AND 
              SIRES01.EXAME = 'HG' 
              AND 
              FCH_TRANS.HT_INDEX = SIRES01.ID_SILANEXA 
                   )FROM 1 FOR 7)||' g%'AS HT,
                   
--DATA_COLETA                   
( SELECT
SILANEXA.COLETA  
     FROM SILANEXA SILANEXA
     WHERE SILANEXA.ID  = FCH_TRANS.HT_INDEX
)DATA_COLETA,
--HORA_COLETA                   
( SELECT
SILANEXA.HRCOL  
     FROM SILANEXA SILANEXA
     WHERE SILANEXA.ID  = FCH_TRANS.HT_INDEX
)HORA_COLETA

----TABELA PRINCIPAL-------------------------
FROM (
SELECT
FIRST 1 
ATCABECATEND.TP_ATENDIMENTO,--TIPO DE ATENDIMENTO
ATCABECATEND.DATA_HORA_ENTRADA,

---- PRONTUARIO
(SELECT
RICADPAC.PRONT
FROM
RICADPAC RICADPAC2
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC2.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID
AND RICADPAC2.ID = HTPACIENTE.ID_RICADPAC
)PRONT ,

---- REGISTRO 
CASE
ATCABECATEND.TP_ATENDIMENTO WHEN 'I' THEN
(--REGISTRO INTERNO
SELECT
RICADPAC.REG
FROM
RICADPAC RICADPAC
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID)
--REGISTRO EXTERNO
WHEN 'E' THEN (
SELECT
RECADATE.REG
FROM
RECADATE RECADATE
INNER JOIN ATCABECATEND ATCABECATEND02 ON
ATCABECATEND02.ID = RECADATE.ID_ATCABECATEND
WHERE
ATCABECATEND02.ID = ATCABECATEND.ID )END 
REGISTRO,

---CARTAO NAC-SAUDE
--  IIF(RICADPAC.CNS = 0, RICADPAC.CNS,'N/A'),
RICADPAC.CNS,

-- NOME 
(
SELECT
RICADPAC.NOME
FROM
RICADPAC RICADPAC
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID
)PACIENTE,
-- NOME SOCIAL
(
SELECT
RICADPAC.APELIDO 
FROM
RICADPAC RICADPAC
INNER JOIN ATCABECATEND ATCABECATEND03 ON
ATCABECATEND03.ID_RICADPAC = RICADPAC.ID
WHERE
ATCABECATEND03.ID = ATCABECATEND.ID
)PACIENTE_SOCIAL,

----DATA DE NASCIMENTO
RICADPAC.NASC AS NASC,

-- IDADE
CASE
WHEN EXTRACT(MONTH
FROM
RICADPAC.NASC)* 100 + EXTRACT(DAY   FROM RICADPAC.NASC)<= EXTRACT (MONTH
FROM CURRENT_DATE)* 100 + EXTRACT(DAY   FROM CURRENT_DATE) THEN EXTRACT(YEAR
FROM CURRENT_DATE)-EXTRACT(YEAR FROM RICADPAC.NASC)
ELSE EXTRACT(YEAR
FROM CURRENT_DATE)-EXTRACT(YEAR FROM RICADPAC.NASC)-1
END || 'a' ||
--MES
CASE
WHEN EXTRACT(MONTH  FROM RICADPAC.NASC)<= EXTRACT(MONTH FROM CURRENT_DATE)  AND
EXTRACT(DAY FROM RICADPAC.NASC)<= EXTRACT(DAY FROM  CURRENT_DATE)
THEN EXTRACT(MONTH FROM CURRENT_DATE)-EXTRACT(MONTH FROM RICADPAC.NASC)
WHEN EXTRACT(MONTH FROM RICADPAC.NASC)<= EXTRACT(MONTH  FROM CURRENT_DATE)AND
EXTRACT(DAY FROM RICADPAC.NASC)>EXTRACT(DAY FROM CURRENT_DATE) THEN EXTRACT(MONTH
FROM CURRENT_DATE)-EXTRACT(MONTH FROM RICADPAC.NASC)-1  WHEN
EXTRACT(MONTH FROM RICADPAC.NASC)>EXTRACT(MONTH FROM CURRENT_DATE)AND
EXTRACT(DAY FROM RICADPAC.NASC)<EXTRACT(DAY FROM CURRENT_DATE) THEN
EXTRACT(MONTH FROM CURRENT_DATE)-EXTRACT(MONTH FROM RICADPAC.NASC)+ 12 ELSE
EXTRACT(MONTH FROM  CURRENT_DATE)-EXTRACT(MONTH FROM
RICADPAC.NASC)+ 11
END || 'm' ||
--DIA------------------------------
CASE   WHEN EXTRACT(DAY FROM RICADPAC.NASC)>EXTRACT(DAY FROM CURRENT_DATE) THEN EXTRACT(DAY
FROM CURRENT_DATE)-EXTRACT(DAY FROM RICADPAC.NASC)+ 31
ELSE EXTRACT(DAY FROM CURRENT_DATE)-EXTRACT(DAY
FROM RICADPAC.NASC)
END || 'd' IDADE,

--SEXO---
CASE
RICADPAC.SEXO WHEN 'M' THEN 'MASCULINO'
WHEN 'F' THEN 'FEMININO'
END SEXO,

---NOME DA MAE
RICADPAC.MAE,
--RELIGIAO
UPPER(TBRELIG.NOME)AS RELIGIAO,

---CONTATO TELEFONICO---
IIF(RICADPAC.CELULAR = 0, 'N/A','('||
SUBSTRING(RICADPAC.CELULAR FROM 1 FOR  2  ) || ')' || -- INICIA NA PRIMEIRA POSICAO E SELECIONA ATÉ A SEGUNDA POSICAO
SUBSTRING( RICADPAC.CELULAR FROM 3 FOR  STRLEN(RICADPAC.CELULAR))) AS CELULAR,
IIF(RICADPAC.FONE = 0, 'N/A','('||
SUBSTRING(RICADPAC.FONE FROM 1 FOR  2  ) || ')' || -- INICIA NA PRIMEIRA POSICAO E SELECIONA ATÉ A SEGUNDA POSICAO
SUBSTRING( RICADPAC.FONE FROM 3 FOR  STRLEN(RICADPAC.FONE))) AS FONE,
IIF(RICADPAC.FCONT = ' ','N/A','('||
SUBSTRING(RICADPAC.FCONT FROM 1 FOR  2  ) || ')' || -- INICIA NA PRIMEIRA POSICAO E SELECIONA ATÉ A SEGUNDA POSICAO
SUBSTRING( RICADPAC.FCONT FROM 3 FOR  STRLEN(RICADPAC.FCONT)))  AS TELEFONE_CONT,

(SELECT--TELEFONE RESIDENCIAL
'('||
SUBSTRING( RICADINT_TEL.TELRESP FROM 1 FOR  2  ) || ')' || -- INICIA NA PRIMEIRA POSICAO E SELECIONA ATÉ A SEGUNDA POSICAO
SUBSTRING( RICADINT_TEL.TELRESP FROM 3 FOR  STRLEN(RICADINT_TEL.TELRESP))-- CONTA O TOTAL DE CARACTERES(STRLEN) E SELECIONA APARTIR DA 3 POSICAO
FROM RICADINT RICADINT_TEL
INNER JOIN ATCABECATEND ATCABECATEND_TEL_RES ON ATCABECATEND_TEL_RES.ID = RICADINT_TEL.ID_ATCABECATEND
WHERE   ATCABECATEND_TEL_RES.ID = ATCABECATEND.ID
)AS TEL_RESI,
----

-- LEITO 
IIF(ATCABECATEND.ID_TBLEITO IS NULL,
'LEITO DE OBSERVAÇÃO',
(
SELECT
TBLEITO.COD_LEITO
FROM
TBLEITO TBLEITO
INNER JOIN ATCABECATEND ATCABECATEND_LEITO ON
ATCABECATEND_LEITO.ID_TBLEITO = TBLEITO.ID
WHERE
ATCABECATEND.ID = ATCABECATEND_LEITO.ID ) ) AS LEITO ,

--CLINICA-
(SELECT
UPPER( TBCLINICA.NOME)
FROM TBCLINICA TBCLINICA
INNER JOIN ATCABECATEND ATCABECATEND_CLINICA ON ATCABECATEND_CLINICA.ID_TBCLINICA = TBCLINICA.COD
WHERE
ATCABECATEND.ID =  ATCABECATEND_CLINICA.ID
)AS CLINICA,

--CONVENIO
(SELECT
TBCONVEN_CONV.COD
FROM TBCONVEN TBCONVEN_CONV
INNER JOIN ATCABECATEND ATCABECATEND_CONV ON ATCABECATEND_CONV.ID_TBCONVEN = TBCONVEN_CONV.COD
WHERE ATCABECATEND_CONV.ID = ATCABECATEND.ID
)CONV_COD,
(SELECT
TBCONVEN_CONV.NOME
FROM TBCONVEN TBCONVEN_CONV
INNER JOIN ATCABECATEND ATCABECATEND_CONV ON ATCABECATEND_CONV.ID_TBCONVEN = TBCONVEN_CONV.COD
WHERE ATCABECATEND_CONV.ID = ATCABECATEND.ID
)CONV_NOME,

-- MEDICO RESPONSAVEL ------------------------
CASE
ATCABECATEND.TP_ATENDIMENTO WHEN 'E' THEN
--RECEPÇÃO EXTERNA - CADASTRO DOS ATENDIMENTOS
(
SELECT
RECADATE.NOME_MED
FROM
RECADATE RECADATE
INNER JOIN ATCABECATEND ATCABECATEND_MEDICO_EXT ON
ATCABECATEND_MEDICO_EXT.ID = RECADATE.ID_ATCABECATEND
WHERE
ATCABECATEND_MEDICO_EXT.ID = ATCABECATEND.ID )
--RECEPÇÃO INTERNA - CADASTRO DE PACIENTES
WHEN 'I' THEN (
SELECT
RICADINT_MEDICO.MEDICO
FROM
RICADINT RICADINT_MEDICO
INNER JOIN ATCABECATEND ATCABECATEND_MED_INT ON
ATCABECATEND_MED_INT.ID = RICADINT_MEDICO.ID_ATCABECATEND
WHERE
ATCABECATEND_MED_INT.ID = ATCABECATEND.ID )
END MEDICO_INT_EXT,

--ENDERECO
RICADPAC.ENDERECO AS RUA,
RICADPAC.NUMERO AS NUM_END,
RICADPAC.BAIRRO AS BAIRRO,
RICADPAC.CIDADE AS CIDADE,
RICADPAC.UF AS UF_END,

--SANGUE
RICADPAC.SANGUE AS SANGUE,
RICADPAC.FATORRH  AS FATOR_RH,

--RESULTADO  HG
--SHTRANS."DATA"  AS DATA_CAD,
   (SELECT FIRST 1 
    MAX(SIRES01.ID_SILANEXA) 
    FROM SIRES01 
    WHERE 
    SIRES01.REG = ATCABECATEND.COD_ATENDIMENTO
    AND SIRES01.EXAME='HG'
    AND SIRES01.ELEMENTO= 3
     )HB_INDEX,
     (SELECT FIRST 1 
    MAX(SIRES01.ID_SILANEXA) 
    FROM SIRES01 
    WHERE 
    SIRES01.REG = ATCABECATEND.COD_ATENDIMENTO
    AND SIRES01.EXAME='HG'
    AND SIRES01.ELEMENTO= 4
     )HT_INDEX
     
FROM
ATCABECATEND ATCABECATEND
INNER JOIN HTATENDIMENTO HTATENDIMENTO ON
HTATENDIMENTO.ID_ATCABECATEND = ATCABECATEND.ID
INNER JOIN TBUNIDAD TBUNIDAD ON
TBUNIDAD.COD = HTATENDIMENTO.ID_TBUNIDAD
INNER JOIN RICADPAC RICADPAC ON
RICADPAC.ID = ATCABECATEND.ID_RICADPAC
INNER JOIN HTPACIENTE HTPACIENTE ON
HTPACIENTE.ID_RICADPAC = RICADPAC .ID
INNER JOIN TBRELIG TBRELIG ON
TBRELIG.COD = RICADPAC.RELIG
--INNER JOIN SHTRANS SHTRANS ON 
--SHTRANS.REG  = ATCABECATEND.COD_ATENDIMENTO 
--AND SHTRANS.ATEND = ATCABECATEND.TP_ATENDIMENTO
--RIGHT  JOIN SHPRETRA SHPRETRA ON
--SHPRETRA.ID_PRETRANS = SHTRANS.ID_SHPRETRA
--INNER JOIN SHBOLSA SHBOLSA ON 
--SHBOLSA.ID_BOLSA = SHPRETRA.ID_BOLSA

WHERE
ATCABECATEND.COD_ATENDIMENTO=:ATENDIMENTO_REGISTRO
AND
RICADPAC.PRONT=:PACIENTE_PRONTUARIO
--ORDER BY ATCABECATEND.ID DESC 

)FCH_TRANS