-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 17 de jan. de 2023
-- Time: 12:54:16
-- By Analista Wesley

/*
 * view epimed
 * prontuario
 * cpf
 * rg
 * nome paciente
 * sexo 
 * data de nascimento
 * convenio
 * hospital code CAST(NULL AS VARCHAR(10)) AS HOSPITALCODE,
 * registro 
 * data/hora entrada
 * bloco
 * cod atendimento
 * data/hora na unidade
 * id do leito
 * RICADINT.MOTIVO  AS DISCHARGECAUSE,
 *  linha 37 a 65 da view V_INTEGRACAO_SCMI_X_EPIMED
 * 
 * 
 * 
 * */

--WITH   CTE_RILEITOS AS (
-- SELECT 
-- RILEITOS.ID,
-- RILEITOS.BLOCO,
-- RILEITOS.ACOMOD,
-- RILEITOS.LEITO 
-- FROM 
-- RILEITOS 
--)

SELECT 
--DISTINCT  
--RICADPAC.PRONT AS MEDICALRECORD,
--RICADPAC.CPF,
--RICADPAC.IDENT,
--RICADPAC.NOME,
--RILEITOS.ANDAR,
--RICTRLOC.BLOCO AS blocoLOC, 
--RILEITOS.BLOCO,
--RICTRLOC.LEITO AS leitoLOC2,
--RILEITOS.LEITO,
--RICTRLOC.ACOMOD acomodLOC2,
--RILEITOS.ACOMOD, 

--RICADINT.ENTRADA,
 RICADPAC.PRONT AS MEDICALRECORD,
            CASE
                WHEN RICADPAC.CPF > 0 THEN 'BR.CPF'
                WHEN RICADPAC.IDENT <> '' THEN 'BR.RG'
                   ELSE 'BR.O'
            END DOCUMENTTYPECODE,
            CASE    WHEN RICADPAC.IDENT <> '' THEN RICADPAC.IDENT
                    WHEN RICADPAC.CPF > 0 THEN RICADPAC.CPF
                  ELSE 0
            END DOCUMENTNUMBER,
             RICADPAC.NOME  AS PATIENTNAME,
            DECODE(
                    RICADPAC.SEXO,'F','F',
                    RICADPAC.SEXO,'M','M',
                    RICADPAC.SEXO,'I','U')GENDER,
          CAST( extract(YEAR FROM RICADPAC.NASC ) || '-'  ||
                  lpad( extract(MONTH FROM RICADPAC.NASC ),2,0) || '-'  ||
                  LPAD( extract(DAY FROM RICADPAC.NASC),2,0) AS varchar(10)) AS      BIRTHDATE ,
     ATCABECATEND.ID_TBCONVEN  AS HOSPITALHEALTHINSURANCECODE ,
     CAST(NULL AS VARCHAR(10)) AS HOSPITALCODE,
     ATCABECATEND.COD_ATENDIMENTO AS HOSPITALADMISSIONNUMBER,
     SUBSTRING( ATCABECATEND.DATA_HORA_ENTRADA FROM 1 FOR 10) HOSPITALADMISSIONDATE,
     RICTRLOC.bloco AS UNITCODE,
     ATCABECATEND.COD_ATENDIMENTO AS UNITADMISSIONNUMBER,
     EXTRACT (YEAR FROM RICTRLOC.ENTRADA) || '-' ||
             LPAD(EXTRACT (MONTH FROM RICTRLOC.ENTRADA),2,0) || '-' ||
             LPAD(EXTRACT (DAY FROM RICTRLOC.ENTRADA),2,0) || ' ' ||
             LPAD(SUBSTR(RICTRLOC.HORAENT,1,2),2,0) || ':' ||
             LPAD(SUBSTR(RICTRLOC.HORAENT,3,4),2,0) || ':00' AS UNITADMISSIONDATETIME,

( SELECT ID  FROM RILEITOS RILEITOS_ID WHERE (
     RILEITOS_ID.BLOCO = RICTRLOC.BLOCO 
     AND 
     RILEITOS_ID.ACOMOD  = RICTRLOC.ACOMOD  
     AND
     RILEITOS_ID.LEITO  = RICTRLOC.LEITO  )  )AS BEDCODE,
              
     RICADINT.MOTIVO  AS DISCHARGECAUSE,
         CASE
             WHEN CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS DATE) IS NULL
                     THEN EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA) || '-' ||
                          LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0) || '-' ||
                              LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0) || ' ' ||
                                LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),1,2),2,0) || ':' ||
                                   LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),4,5),2,0) || ':' ||
                                   LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),7,8),2,0)
             ELSE EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_SAIDA_EFETIVA) || '-' ||
                 LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_SAIDA_EFETIVA),2,0) || '-' ||
                     LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_SAIDA_EFETIVA),2,0) || ' ' ||
                       LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS TIME),1,2),2,0) || ':' ||
                          LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS TIME),4,5),2,0) || ':' ||
                             LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS TIME),7,8),2,0)
          END AS HOSPITALDISCHARGEDATE,
      EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA) || '-' ||
         LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0) || '-' ||
            LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0)  || ' ' ||
              LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),1,2),2,0) || ':' ||
              LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),4,5),2,0) || ':' ||
                 LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),7,8),2,0
                        ) AS MEDICALDISCHARGEDATE,
       EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_INCLUSAO) || '-' ||
         LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_INCLUSAO),2,0) || '-' ||
             LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_INCLUSAO),2,0) || ' ' ||
              LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_INCLUSAO AS TIME),1,2),2,0) || ':' ||
                LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_INCLUSAO AS TIME),4,5),2,0) || ':' ||
                  LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_INCLUSAO AS TIME),7,8),2,0
                           ) AS CREATEDATE,
    COALESCE( 'R.: ' ||
         (TRIM(RICADPAC.ENDERECO))
              ||',N?:'||RICADPAC.NUMERO
              ||',BAIRRO: '||TRIM(RICADPAC.BAIRRO)
              ||',CIDADE: '||RICADPAC.CIDADE
              ||'-'||RICADPAC.UF
              ||',CEP.: '||RICADPAC.CEP,'N/A')  AS ADDRESS,
    IIF(RICADPAC.FONE = ' ','0',RICADPAC.FONE)TELEPHONE


FROM ATCABECATEND ATCABECATEND  /*Atendimento -Cabecalho de atendimento*/
JOIN RICADPAC RICADPAC ON ATCABECATEND.ID_RICADPAC = RICADPAC.ID /*Cadastro de Paciente*/ 
JOIN RICADINT RICADINT ON RICADINT.ID_ATCABECATEND = ATCABECATEND.ID /*Recepção Interna - Cadastro de internações*/ 
--JOIN RILEITOS RILEITOS ON RICADINT.ID_RILEITOS = RILEITOS.ID /*Recepção Interna - Cadastro de leitos*/  
JOIN RICTRLOC RICTRLOC ON RICTRLOC.REG = RICADINT.REG  /*Recepção Interna - Controle de localizações*/
where ((atcabecatend.data_hora_alta_medica >= current_timestamp - 20) or (atcabecatend.data_hora_alta_medica is null))
      and atcabecatend.tp_atendimento = 'I'








