-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 18 de jan. de 2023
-- Time: 13:46:41
-- By Analista Wesley
/*
 * 
 * 
 * */
SELECT DISTINCT 

RILEITOS.BLOCO AS C_INTERNO_DO_SETOR_UNIDADE,
 RIBLOCOS.NOME AS NOME_DO_SETOR_UNIDADE,
RILEITOS.ID AS CD_INTERNO_DO_LEITO,
RILEITOS.LEITO  AS DESCRICAO_DO_LEITO,
(   
 SELECT 
 FIRST 1
 TBACOMODLEITO_II.NOME
 FROM TBACOMODLEITO TBACOMODLEITO_II
 WHERE 
 ( TBACOMODLEITO_II.ID_RIBLOCOS = RIBLOCOS.BLOCO 
 AND
 TBACOMODLEITO_II.COD_ACOMODACAO = RILEITOS.ACOMOD  )
)DESCRIÇÃO_DO_LEITO,
 ' ' AS SN_EXTRA,
' 'AS SN_mais_24h,
RILEITOS.STATUS AS STATUS

FROM RILEITOS RILEITOS 
JOIN RIBLOCOS RIBLOCOS ON RIBLOCOS.BLOCO = RILEITOS.BLOCO 
JOIN TBACOMODLEITO TBACOMODLEITO ON TBACOMODLEITO.ID_RIBLOCOS =RIBLOCOS.BLOCO 
--WHERE 
--RIBLOCOS.BLOCO IS NOT DISTINCT FROM 'CL-C'
 
