-- CONNECTION: name=PROD



--
-- New script in PROD.
-- Date: 12 de dez. de 2022
-- Time: 10:13:20
-- By Wesley
--SELECT FIRST 20
--
--ATCABECATEND.*
--FROM ATCABECATEND ATCABECATEND 
--WHERE 
--ATCABECATEND.TP_ATENDIMENTO = 'I'
--AND 
--ATCABECATEND.COD_ATENDIMENTO = 53950
--ORDER BY DATA_HORA_ENTRADA DESC 


-- Auto-generated SQL script. Actual values for binary/complex data types may differ - what you see is the default string representation of values.
-- CONNECTION: name=PROD

-- New script in LOCAL.
-- Date: 2 de dez. de 2022
-- Time: 13:56:57
-- By Wesley

SELECT DISTINCT 


TBFLUXOATEND.ACAO ,

TBFLUXOATEND.ID AS ID_TBFLUXOATEND

FROM 

  

(

SELECT
DISTINCT 
-- TBFLUXOATEND.ID_TBSENHAATEND,
MAX(TBFLUXOATEND.ID) OVER ( PARTITION BY TBFLUXOATEND.ID_TBSENHAATEND ORDER BY TBFLUXOATEND.DATA_HORA DESC )I 
FROM 
TBFLUXOATEND 
) FLUXO
JOIN TBFLUXOATEND ON TBFLUXOATEND.ID =FLUXO.I 
JOIN TBSENHAATEND ON TBFLUXOATEND.ID_TBSENHAATEND = TBSENHAATEND.ID
JOIN ATCABECATEND_TBSENHAATEND ON ATCABECATEND_TBSENHAATEND.ID_TBSENHAATEND = TBSENHAATEND.ID 
JOIN RECADATE ON RECADATE.ID_ATCABECATEND = ATCABECATEND_TBSENHAATEND.ID_ATCABECATEND 
JOIN HTATENDIMENTO HTATENDIMENTO ON HTATENDIMENTO.ID_ATCABECATEND = ATCABECATEND_TBSENHAATEND.ID_ATCABECATEND
JOIN ATCABECATEND ON HTATENDIMENTO.ID_ATCABECATEND  = ATCABECATEND.ID 
JOIN TBCLINICA TBCLINICA ON TBCLINICA.COD = HTATENDIMENTO.ID_TBCLINICA 
JOIN TBLOCAL ON TBFLUXOATEND.ID_TBLOCAL = TBLOCAL.ID 
WHERE 
TBFLUXOATEND.ACAO NOT SIMILAR TO 'L'
AND 
TBFLUXOATEND.ACAO NOT SIMILAR TO 'N'
AND 
TBCLINICA.COD = 'S'
AND 
ATCABECATEND.DATA_HORA_ENTRADA  < DATEADD(-3 DAY TO CURRENT_TIMESTAMP ) 
--AND 
------ATCABECATEND.DATA_HORA_ENTRADA   >= (CURRENT_DATE) || ' 00:01:01.000'
--ATCABECATEND.DATA_HORA_ENTRADA  BETWEEN  dateadd(-480 HOUR  TO  CURRENT_TIMESTAMP ) AND  dateadd(12 HOUR  to CURRENT_TIMESTAMP )

ORDER BY 
TBFLUXOATEND.ID DESC 









