-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 23 de nov. de 2022
-- Time: 11:42:29
-- By Wesley


-- V_INTEGRACAO_SCMI_X_EPIMED source

--CREATE OR ALTER VIEW V_INTEGRACAO_SCMI_X_EPIMED (MEDICALRECORD,
 DOCUMENTTYPECODE, DOCUMENTNUMBER, PATIENTNAME, GENDER, BIRTHDATE, 
 HOSPITALHEALTHINSURANCECODE, HOSPITALCODE, HOSPITALADMISSIONNUMBER, HOSPITALADMISSIONDATE,
 UNITCODE, UNITADMISSIONNUMBER, UNITADMISSIONDATETIME, BEDCODE, UNITDISCHARGEDATETIME, 
 DISCHARGECAUSE, HOSPITALDISCHARGEDATE,
 MEDICALDISCHARGEDATE, CREATEDATE, ADDRESS, TELEPHONE)
--AS
SELECT
    RICADPAC.PRONT AS MEDICALRECORD,
            CASE
                WHEN RICADPAC.CPF > 0 THEN 'BR.CPF'
                WHEN RICADPAC.IDENT <> '' THEN 'BR.RG'
                   ELSE 'BR.O'
            END DOCUMENTTYPECODE,
            CASE    WHEN RICADPAC.IDENT <> '' THEN RICADPAC.IDENT
                    WHEN RICADPAC.CPF > 0 THEN RICADPAC.CPF
                  ELSE 0
            END DOCUMENTNUMBER,
--            RICADPAC.CPF,
    RICADPAC.NOME  AS PATIENTNAME,
            DECODE(
                    RICADPAC.SEXO,'F','F',
                    RICADPAC.SEXO,'M','M',
                    RICADPAC.SEXO,'I','U')GENDER,
            RICADPAC.NASC  AS BIRTHDATE ,
     ATCABECATEND.ID_TBCONVEN  AS HOSPITALHEALTHINSURANCECODE ,
     CAST(NULL AS VARCHAR(10)) AS HOSPITALCODE,
     ATCABECATEND.COD_ATENDIMENTO AS HOSPITALADMISSIONNUMBER,
     SUBSTRING( ATCABECATEND.DATA_HORA_ENTRADA FROM 1 FOR 10) HOSPITALADMISSIONDATE,
     RICTRLOC.ACOMOD AS UNITCODE,
     ATCABECATEND.COD_ATENDIMENTO AS UNITADMNISSIONNUMBER,
     EXTRACT (YEAR FROM RICTRLOC.ENTRADA) || '-' ||
             LPAD(EXTRACT (MONTH FROM RICTRLOC.ENTRADA),2,0) || '-' ||
             LPAD(EXTRACT (DAY FROM RICTRLOC.ENTRADA),2,0) || ' ' ||
             LPAD(SUBSTR(RICTRLOC.HORAENT,1,2),2,0) || ':' ||
             LPAD(SUBSTR(RICTRLOC.HORAENT,3,4),2,0) || ':00' AS UNITADMISSIONDATETIME,
     RICTRLOC.LEITO AS BEDCODE,
     RICADINT.MOTIVO  AS DISCHARGECAUSE,
         CASE
             WHEN CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS DATE) IS NULL
                     THEN EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA) || '-' ||
                          LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0) || '-' ||
                              LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0) || ' ' ||
                                LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),1,2),2,0) || ':' ||
                                   LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),4,5),2,0) || ':' ||
                                   LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),7,8),2,0)
             ELSE EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_SAIDA_EFETIVA) || '-' ||
                 LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_SAIDA_EFETIVA),2,0) || '-' ||
                     LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_SAIDA_EFETIVA),2,0) || ' ' ||
                       LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS TIME),1,2),2,0) || ':' ||
                          LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS TIME),4,5),2,0) || ':' ||
                             LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_SAIDA_EFETIVA AS TIME),7,8),2,0)
          END AS HOSPITALDISCHARGEDATE,
      EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA) || '-' ||
         LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0) || '-' ||
            LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_ALTA_MEDICA),2,0)  || ' ' ||
              LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),1,2),2,0) || ':' ||
              LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),4,5),2,0) || ':' ||
                 LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_ALTA_MEDICA AS TIME),7,8),2,0
                        ) AS MEDICALDISCHARGEDATE,
       EXTRACT (YEAR FROM ATCABECATEND.DATA_HORA_INCLUSAO) || '-' ||
         LPAD(EXTRACT (MONTH FROM ATCABECATEND.DATA_HORA_INCLUSAO),2,0) || '-' ||
             LPAD(EXTRACT (DAY FROM ATCABECATEND.DATA_HORA_INCLUSAO),2,0) || ' ' ||
              LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_INCLUSAO AS TIME),1,2),2,0) || ':' ||
                LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_INCLUSAO AS TIME),4,5),2,0) || ':' ||
                  LPAD(SUBSTR(CAST(ATCABECATEND.DATA_HORA_INCLUSAO AS TIME),7,8),2,0
                           ) AS CREATEDATE,
    COALESCE( 'R.: ' ||
         (TRIM(RICADPAC.ENDERECO))
              ||',N?:'||RICADPAC.NUMERO
              ||',BAIRRO: '||TRIM(RICADPAC.BAIRRO)
              ||',CIDADE: '||RICADPAC.CIDADE
              ||'-'||RICADPAC.UF
              ||',CEP.: '||RICADPAC.CEP,'N/A')  AS ADDRESS,
    IIF(RICADPAC.FONE = ' ','0',RICADPAC.FONE)TELEPHONE
    FROM ATCABECATEND ATCABECATEND
    INNER JOIN RICADPAC  RICADPAC ON RICADPAC.ID = ATCABECATEND.ID_RICADPAC
    INNER JOIN TBLEITO TBLEITO ON TBLEITO.ID = ATCABECATEND.ID_TBLEITO
    INNER JOIN TBACOMODLEITO TBACOMODLEITO ON TBACOMODLEITO.ID = TBLEITO.ID_TBACOMODLEITO
    INNER JOIN RICADINT RICADINT ON RICADINT.ID_ATCABECATEND = ATCABECATEND.ID
    INNER JOIN TBCLINICA TBCLINICA ON TBCLINICA.COD =  ATCABECATEND.ID_TBCLINICA
    INNER JOIN RICTRLOC RICTRLOC ON RICTRLOC.REG = RICADINT.REG
       WHERE
    ATCABECATEND.TP_ATENDIMENTO = 'I'
    AND
    DATA_HORA_ENTRADA >='2020-01-01 ' || '00:00:00.000';