-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 7 de dez. de 2022
-- Time: 15:09:02
-- By Wesley
SELECT --TBLEITO.*,
RIBLOCOS.BLOCO AS COD_INTER,
RIBLOCOS.NOME AS NOME_SET,
TBLEITO.ID AS ID_LEITO,
TBLEITO.COD_LEITO AS DESC_LEITO,
TBACOMODLEITO.NOME  AS TIPO_ACOMOD

FROM TBLEITO
INNER JOIN TBACOMODLEITO ON TBACOMODLEITO.ID = TBLEITO.ID_TBACOMODLEITO
INNER JOIN RIBLOCOS ON RIBLOCOS.BLOCO  = TBACOMODLEITO.ID_RIBLOCOS 
WHERE 
--RIBLOCOS.BLOCO IN  ('BERC','MAT')
--RIBLOCOS.BLOCO IN  ('BERC','BLCC','C-MED','CLI-M','MAT','UTI')
RIBLOCOS.BLOCO NOT STARTING WITH 'INATIVO'
AND 
--TBACOMODLEITO.NOME NOT IN  ('INATIVO - UTI COVID','INATIVO - UTI5')
TBACOMODLEITO.NOME NOT STARTING WITH  'INATIVO'
AND 
TBLEITO.ATIVO = 'T'