-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 24 de nov. de 2022
-- Time: 13:35:45
-- By Wesley
GRANT SELECT ON ATCABECATEND TO EPIMED;
GRANT SELECT ON RICADPAC TO EPIMED;
GRANT SELECT ON TBLEITO TO EPIMED;
GRANT SELECT ON TBACOMODLEITO TO EPIMED;
GRANT SELECT ON TBCID10 TO EPIMED;
GRANT SELECT ON RICADINT TO EPIMED;
GRANT SELECT ON RICTRLOC TO EPIMED
GRANT SELECT ON TBCLINICA TO EPIMED
