-- CONNECTION: name=PROD
-- New script in PROD.
-- Date: 25 de jan. de 2023
-- Time: 09:58:35
-- By Analista Wesley
SELECT 

*

FROM SEC$USERS su 




CREATE USER RAZIOS PASSWORD 'SGHRAZIOS';




--GRANT SELECT ON REPACAGI TO RAZIOS;
--GRANT SELECT ON SIPACAGI TO RAZIOS;
--GRANT SELECT ON tbsitage TO RAZIOS;
--GRANT SELECT ON sipacagd TO RAZIOS;
--GRANT SELECT ON tbcbopro TO RAZIOS;
--GRANT SELECT ON tbprofis TO RAZIOS;
--GRANT SELECT ON siagenda TO RAZIOS;